// <auto-generated />
using System;
using Clothub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clothub.Persistence.Migrations
{
    [DbContext(typeof(ClothubDbContext))]
    [Migration("20260502183518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clothub.Domain.Entities.Apartado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_limite");

                    b.Property<decimal>("MontoPagado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_pagado");

                    b.Property<decimal>("MontoRestante")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_restante");

                    b.Property<Guid>("PrendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("prenda_id");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("PrendaId", "Estado")
                        .IsUnique()
                        .HasFilter("estado = 'Activo'");

                    b.ToTable("apartados", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("etiquetas", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.EtiquetaPrenda", b =>
                {
                    b.Property<Guid>("PrendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("prenda_id");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etiqueta_id");

                    b.HasKey("PrendaId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("etiquetas_prenda", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.FotoPrenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("PrendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("prenda_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PrendaId", "Orden")
                        .IsUnique();

                    b.ToTable("fotos_prenda", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("canton");

                    b.Property<string>("CodigoRastreo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_rastreo");

                    b.Property<decimal>("Comision")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("comision");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_id");

                    b.Property<decimal>("CostoEnvio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_envio");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion_exacta");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("distrito");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_total");

                    b.Property<decimal>("MontoVendedor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_vendedor");

                    b.Property<string>("NombreDestinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_destinatario");

                    b.Property<Guid>("PrendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("prenda_id");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provincia");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<string>("TelefonoDestinatario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono_destinatario");

                    b.Property<Guid>("TiendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tienda_id");

                    b.Property<string>("TipoEnvio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_envio");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("Estado");

                    b.HasIndex("PrendaId");

                    b.HasIndex("TiendaId");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Prenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("condicion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<decimal?>("MedidaAncho")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("medida_ancho");

                    b.Property<decimal?>("MedidaCintura")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("medida_cintura");

                    b.Property<decimal?>("MedidaLargo")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("medida_largo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("talla");

                    b.Property<Guid>("TiendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tienda_id");

                    b.Property<string>("TipoPrenda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_prenda");

                    b.Property<int>("Vistas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vistas");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaPublicacion");

                    b.HasIndex("TiendaId");

                    b.ToTable("prendas", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("TiendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tienda_id");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("TiendaId", "Estado");

                    b.ToTable("reportes", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Resena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comentario");

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid>("TiendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tienda_id");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.HasIndex("TiendaId");

                    b.ToTable("resenas", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Seguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EtiquetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("etiqueta_id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("TiendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tienda_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("TiendaId");

                    b.HasIndex("UsuarioId", "EtiquetaId")
                        .IsUnique()
                        .HasFilter("etiqueta_id IS NOT NULL");

                    b.HasIndex("UsuarioId", "TiendaId")
                        .IsUnique()
                        .HasFilter("tienda_id IS NOT NULL");

                    b.ToTable("seguimientos", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Tienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AceptaApartados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("acepta_apartados");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("instagram");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<decimal?>("PorcentajeApartado")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_apartado");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provincia");

                    b.Property<string>("ReglasDeLaTienda")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reglas_de_la_tienda");

                    b.Property<string>("StripeAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_account_id");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<bool>("TelefonoVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("telefono_verificado");

                    b.Property<int?>("TiempoLimiteApartadoHoras")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_limite_apartado_horas");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("tiendas", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verificado");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proveedor_auth");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<string>("TokenVerificacionEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token_verificacion_email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("google_id IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Apartado", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Usuario", "Comprador")
                        .WithMany("Apartados")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothub.Domain.Entities.Prenda", "Prenda")
                        .WithMany("Apartados")
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.EtiquetaPrenda", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Etiqueta", "Etiqueta")
                        .WithMany("Prendas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clothub.Domain.Entities.Prenda", "Prenda")
                        .WithMany("Etiquetas")
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.FotoPrenda", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Prenda", "Prenda")
                        .WithMany("Fotos")
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prenda");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Usuario", "Comprador")
                        .WithMany("Pedidos")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothub.Domain.Entities.Prenda", "Prenda")
                        .WithMany("Pedidos")
                        .HasForeignKey("PrendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothub.Domain.Entities.Tienda", "Tienda")
                        .WithMany("Pedidos")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Prenda");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Prenda", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Tienda", "Tienda")
                        .WithMany("Prendas")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Usuario", "Comprador")
                        .WithMany("Reportes")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothub.Domain.Entities.Tienda", "Tienda")
                        .WithMany("Reportes")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Resena", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Usuario", "Comprador")
                        .WithMany("Resenas")
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothub.Domain.Entities.Pedido", "Pedido")
                        .WithOne("Resena")
                        .HasForeignKey("Clothub.Domain.Entities.Resena", "PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clothub.Domain.Entities.Tienda", "Tienda")
                        .WithMany("Resenas")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Pedido");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Seguimiento", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Etiqueta", "Etiqueta")
                        .WithMany("Seguimientos")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Clothub.Domain.Entities.Tienda", "Tienda")
                        .WithMany("Seguimientos")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Clothub.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Seguimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Tienda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Tienda", b =>
                {
                    b.HasOne("Clothub.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Tienda")
                        .HasForeignKey("Clothub.Domain.Entities.Tienda", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Etiqueta", b =>
                {
                    b.Navigation("Prendas");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Resena");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Prenda", b =>
                {
                    b.Navigation("Apartados");

                    b.Navigation("Etiquetas");

                    b.Navigation("Fotos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Tienda", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Prendas");

                    b.Navigation("Reportes");

                    b.Navigation("Resenas");

                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("Clothub.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Apartados");

                    b.Navigation("Pedidos");

                    b.Navigation("Reportes");

                    b.Navigation("Resenas");

                    b.Navigation("Seguimientos");

                    b.Navigation("Tienda");
                });
#pragma warning restore 612, 618
        }
    }
}
